server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9194/eureka
spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.bear.management.stock.notificationservice.event.OrderPlacedEvent
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: ms-notifications