server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9194/eureka
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/api/product/**
        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/api/order/**
        - id: ms-inventories
          uri: lb://ms-inventories
          predicates:
            - Path=/api/inventory/**
        - id: ms-discovery-server
          uri: http://localhost:9194
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: ms-discovery-server-static
          uri: http://localhost:9194
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9190/realms/microservices-stock-realm
  application:
    name: ms-api-gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO