server:
  port: 9194
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: ms-discovery-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
app:
  eureka:
    username: eureka
    password: password
