server:
  port: 9194
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: ms-discovery-server
app:
  eureka:
    username: eureka
    password: password
