server:
  port: 9192
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:9194/eureka
spring:
  application:
    name: ms-products
  data:
    mongodb:
      database: product-service
      port: 27017
      host: localhost
info:
  app:
    name: Secure Platform Solutions Microservice Products
    version: 1.0
    decription: CRUD Products Microservice